AllCops:
  Excludes:
    - vendor/**
    - chef/cookbooks/**
    - tmp/**
    - .librarian/**
    - .vagrant/**
    - .chef/**

Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
StringLiterals:
  Enabled: false
WordArray:
  Enabled: false
NumericLiterals:
  Enabled: false
