site :opscode

cookbook "application"
cookbook "application_ruby"
cookbook "apt", "1.9.0"
cookbook "aws"
cookbook "bash-completion"
cookbook "build-essential"
cookbook "curl"
cookbook "datadog"
cookbook "denyhosts", git: "https://github.com/phlipper/chef-denyhosts"
cookbook "elasticsearch", git: "https://github.com/elasticsearch/cookbook-elasticsearch"
cookbook "git"
cookbook "grc"
cookbook "hostname", "~> 0.1.0"
cookbook "htop"
cookbook "iftop"
cookbook "imagemagick"
cookbook "iptables", git: "https://github.com/phlipper/iptables"
cookbook "java"
cookbook "jenkins", "~> 1.0"
cookbook "logrotate"
cookbook "logwatch"
cookbook "memcached"
cookbook "monit", git: "https://github.com/phlipper/chef-monit"
cookbook "munin"
cookbook "newrelic-sysmond", "~> 1.3.0"
cookbook "nginx", git: "https://github.com/phlipper/chef-nginx"
cookbook "nodejs", git: "https://github.com/phlipper/chef-nodejs"
cookbook "ntp"
cookbook "openssh"
cookbook "papertrail-rsyslog"
cookbook "postfix"
cookbook "postgresql", git: "https://github.com/phlipper/chef-postgresql"
cookbook "rbenv", git: "https://github.com/fnichol/chef-rbenv"
cookbook "redis", git: "https://github.com/phlipper/chef-redis"
cookbook "resolver", '~> 1.1.4'
cookbook "rsync"
cookbook "ruby_build"
cookbook "screen"
cookbook "sudo"
cookbook "sysstat"
cookbook "user", git: "https://github.com/fnichol/chef-user"
cookbook "xfs"
cookbook "xml"
cookbook "xslt"
cookbook "zlib"
