source 'https://rubygems.org'

gem 'berkshelf',      '~> 2'
gem 'chef',           '~> 10.18'
gem 'foodcritic',     '~> 3.0'
gem 'fpm',            '~> 0.3'
gem 'knife-cookbook-cleanup'
gem 'knife-ec2'
gem 'knife-spork'
gem 'rubocop',        '~> 0.14'
